
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE "Users" IF NOT EXISTS(
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  "passwordHash" VARCHAR(255) NOT NULL,
  role VARCHAR(10) CHECK (role IN ('admin', 'mentor', 'mentee')) NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Mentee" IF NOT EXISTS(
  "menteeId" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "userId" UUID NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  "shortBio" VARCHAR(255) NOT NULL,
  "goals" VARCHAR(255) NOT NULL,
  "username" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Mentor" IF NOT EXISTS (
  "mentorId" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "userId" UUID NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  "shortBio" VARCHAR(255) NOT NULL,
  "goals" VARCHAR(255) NOT NULL,
  "username" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Mentorship Request" IF NOT EXISTS (
  id SERIAL PRIMARY KEY,
  "mentorId" UUID NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  "menteeId" UUID NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Skills" IF NOT EXISTS (
  id SERIAL PRIMARY KEY,
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS "Users"(
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  "passwordHash" VARCHAR(255) NOT NULL,
  role VARCHAR(10) CHECK (role IN ('admin', 'mentor', 'mentee')) NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS  "Mentee"(
  "menteeId" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "userId" UUID NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  "shortBio" VARCHAR(255) NOT NULL,
  "goals" VARCHAR(255) NOT NULL,
  "username" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Mentor" (
  "mentorId" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "userId" UUID NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  "shortBio" VARCHAR(255) NOT NULL,
  "goals" VARCHAR(255) NOT NULL,
  "username" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Mentorship Request" (
  id SERIAL PRIMARY KEY,
  "mentorId" UUID NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  "menteeId" UUID NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Skills" (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "User Skills" (
  "UserId" UUID NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  "SkillId" INTEGER NOT NULL REFERENCES "Skills"(id) ON DELETE CASCADE,
  PRIMARY KEY ("UserId", "SkillId")
);

  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE "User Skills" IF NOT EXISTS (
  "UserId" UUID NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  "SkillId" INTEGER NOT NULL REFERENCES "Skills"(id) ON DELETE CASCADE,
  PRIMARY KEY ("UserId", "SkillId")
);
